name: Test and build
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i yarn -g && yarn install
      - name: Run test command
        run: yarn test:ci
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i yarn -g && yarn install
      - name: Run test command
        run: yarn build
